language: node_js
node_js:
  - "5.1"
sudo: false
script: ./tool/shared/deploy.sh --robots ok default

# Only run Travis jobs for named branches (to avoid double builds for each PR)
branches:
  only: [master, /^\d(\.x|-dev)$/, /travis-build/]
